<?php
$showWishlist = true;
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();
			
            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    default:
        $exist = null;
}
?>

<?php if ($exist):?>
<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php else: ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php endif; ?>
<?php else: ?>
<section class="block <?php echo $class; ?>">
   <?php endif; ?>
	<div class="rokan-product-heading rokan-relate-heading">
		<h2><?php echo $title; ?></h2>
		<div class="description"><?php echo __('Nam liber tempor cum soluta nobis eleifend option congue nihil<br>
doming id quod mazim placerat facer possim assum typi non habent claritatem insitam.') ?></div>
	</div>
	<div class="block-content content" aria-labelledby="block-<?php echo $class?>-heading">
		<div class="row">
			<div id="relate_product_slider_<?php echo $type;?>" class="owl-carousel">
				<?php $iterator = 1; ?>
				<?php 
					$i = 0;
					$rows = 1;
				?>
				<?php foreach ($items as $_item): ?>
				<?php $available = ''; ?>
				<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
				<?php if (!$_item->getRequiredOptions()): ?>
				<?php $available = 'related-available'; ?>
				<?php endif; ?>
				<?php endif; ?>
			<?php
					$productImage = $block->getImage($_item, $image);
			?>	
				<?php if ($i++%$rows==0) { ?>
					<div class="products-item">
				<?php } ?>
					<div class="product-item">
						<div class="item-inner">
							<div class="product-photo">
								<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
									<span class="image0 image-switch">
										<?php echo $productImage->toHtml(); ?>
									</span>
									<span class="image1 image-switch">
										<?php echo $productImageThumb->toHtml(); ?>
									</span>
								</a>
								<div class="addto-links-icons visible-onhover">
									<div class="action-inner">	
										<ul class="add-to-links">
											<?php if( $showWishlist ): ?>
			                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<li>
	                                            <a href="#"
	                                               class="action button towishlist"
	                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
	                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
	                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
	                                               data-action="add-to-wishlist"
	                                               role="button">
	                                               <i class="icon-heart icons"></i>
	                                            </a>
											</li>
											<?php endif; ?>
											<?php endif; ?>

											<li>
												<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
												?>
												<a href="#"
												   class="action tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
												   role="button">
													<i class="icon-equalizer icons"></i>
												</a>
											</li>
											
											<?php if ($this->helper('Rokanthemes\QuickView\Helper\Data')->isEnable()){ ?>
											<li class="quickview-product">
												<a href="javascript:void(0)" data-role="quickview-button" data-id="<?php echo $_item->getId(); ?>" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_item->getId()) ?>" title="<?php echo $block->escapeHtml(__('Quick view')); ?>" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>">
		                                            <i class="icon-eye icons"></i>
		                                         </a>
											</li>
											<?php } ?>
										</ul>	
									</div>
								</div>
								<div class="addto-links-bottom">
									<ul class="add-to-links">
										<li>
											<div class="actions-add-cart">
												<div class="action-inner">
													<div class="actions-primary"> 
														<?php if ($_item->isSaleable()): ?>
															<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
															<button class="action tocart" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php echo __('Add to Cart') ?>">
																<i class="icon-handbag icons"></i>
																<?php echo $block->escapeHtml(__('Add to Cart')); ?>
															</button>
															<?php else: ?>
															<?php 
																$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														   		$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
														    ?>
															<button class="action tocart"
															   data-post='<?php echo $postData; ?>'
															   type="button" title="<?php echo __('Add to Cart') ?>">
																<i class="icon-handbag icons"></i>
																<?php echo $block->escapeHtml(__('Add to Cart')); ?>
															</button>
															<?php endif; ?>
														<?php else: ?>
															<?php if ($_item->getIsSalable()): ?>
																<div class="stock available"><span><?php echo __('In stock') ?></span></div>
															<?php else: ?>
																<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>

													</div>
												</div>
											</div>
										</li>
									</ul>
								</div>
								<div class="product-label">
									<?php if ( $_item->getFinalPrice() < $_item->getPrice() ): ?>
										<?php 
											$percent = ( ($_item->getPrice()-$_item->getFinalPrice()) / ($_item->getPrice()) )*100; 
										?>
										<span class="onsale">
											<span>-<?php echo round($percent); ?>%</span>
										</span>
									<?php endif; ?>
									<?php $todayDate = time(); 
										$timeStartNew = strtotime($_item->getData('news_from_date'));
										$timeEndNew = strtotime($_item->getData('news_to_date')); ?>
									<?php if ( $timeEndNew >= $todayDate && $timeStartNew <= $todayDate): ?>
										<span class="newlabel">
											<span><?php echo __('New') ?></span>
										</span>
									<?php endif; ?>
								</div>
							</div>
							<div class="product-info">
								<strong class="product-item-name">
									<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
									<?php echo $block->escapeHtml($_item->getName()) ?></a>
								</strong>
								<div class="product-ratting-common">
								<?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
								</div>
								<?php echo $block->getProductPrice($_item); ?>		
							</div>
							
						</div>
					</div>
				<?php if($i%$rows==0 || $i == count($items)) { ?> 
				</div> 
				<?php } ?>
				<?php endforeach ?>
			</div>
		</div>
    </div>

</section>
<?php endif;?>
<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';

		jQuery("#relate_product_slider_<?php echo $type;?>").owlCarousel({
			lazyLoad: true,
			autoPlay : false,
			items : 4,
			itemsDesktop : [1199,4],
			itemsDesktopSmall : [980,3],
			itemsTablet: [768,2],
			itemsMobile : [479,1],
			slideSpeed : 500,
			paginationSpeed : 500,
			rewindSpeed : 500,
			navigation : true,
			stopOnHover : true,
			pagination :false,
			scrollPerPage:true,
		});
	});
</script>