<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<div class="container-catalog-products-common">
		<?php
		if ($block->getMode() == 'grid') {
			$viewMode = 'grid';
			$image = 'category_page_grid';
			$showDescription = false;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$col_grid = ' category_page_grid_3';
		} else {
			$viewMode = 'list';
			$image = 'category_page_list';
			$showDescription = true;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			$col_grid = '';
		}
		/**
		 * Position for actions regarding image size changing in vde if needed
		 */
		$pos = $block->getPositioned();
		?>
		<div class="toolbar-html-container-top check-view-mode-toolbar-<?php echo $viewMode;?>" data-mode="<?php echo $viewMode;?>">
		<?= $block->getToolbarHtml() ?>
		</div>
		<?= $block->getAdditionalHtml() ?>
		<div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
			<?php $iterator = 1; ?>
			<div class="row">
				<ol class="container-products-switch products list items product-items<?php echo $col_grid;?>" data-view-mode="3"> 
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
					<?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
					<div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
						<div class="item-inner">
							<?php
							$productImage = $block->getImage($_product, $image);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<?php // Product Image ?>
							<div class="product-photo">
								<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								   <?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
										<span class="image0 image-switch">
											<?php echo $productImage->toHtml(); ?>
										</span>
										<span class="image1 image-switch">
											<?php echo $productImageThumb->toHtml(); ?>
										</span>
								</a>
								<?php if ($block->getMode() == 'grid') { ?>
								<div class="addto-links-icons visible-onhover">
									<div class="action-inner">	
										<ul class="add-to-links">
											<li>
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
													<a href="#" class="action towishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
														<i class="icon-heart icons"></i>
													</a>
												<?php endif; ?>	
											</li>
											<li>
												<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
												?>
												<a href="#"
												   class="action tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
												   role="button">
													<i class="icon-equalizer icons"></i>
												</a>
											</li>
											<?php if ($this->helper('Rokanthemes\QuickView\Helper\Data')->isEnable()){ ?>
											<li class="quickview-product">
												<a href="javascript:void(0)" data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="<?php echo $block->escapeHtml(__('Quick view')); ?>" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>">
													<i class="icon-eye icons"></i>
													<?php //echo $block->escapeHtml(__('Quick View')); ?>
												</a>
											</li>
											<?php } ?>
										</ul>	
									</div>
								</div>
								
								<div class="addto-links-bottom">
									<ul class="add-to-links">
										<li>
											<div class="actions-add-cart">
												<div class="product actions product-item-actions action-inner"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
													<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
														<?php if ($_product->isSaleable()): ?>
															<?php $postParams = $block->getAddToCartPostParams($_product); ?>
															<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
																<input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
																<input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
																<?= $block->getBlockHtml('formkey') ?>
																<button type="submit"
																		title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
																		class="action tocart primary">
																	<i class="icon-handbag icons"></i>
																	<?php echo $block->escapeHtml(__('Add to Cart')); ?>
																</button>
															</form>
														<?php else: ?>
															<?php if ($_product->isAvailable()): ?>
																<div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
															<?php else: ?>
																<div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>
													</div>  
												</div>
											</div>
										</li>
									</ul>
								</div>
								<?php } ?>
								<div class="product-label">
									<?php if ( $_product->getFinalPrice() < $_product->getPrice() ): ?>
										<?php 
											$percent = ( ($_product->getPrice()-$_product->getFinalPrice()) / ($_product->getPrice()) )*100; 
										?>
										<span class="onsale">
											<span>-<?php echo round($percent); ?>%</span>
										</span>
									<?php endif; ?>
									<?php $todayDate = time(); 
										$timeStartNew = strtotime($_product->getData('news_from_date'));
										$timeEndNew = strtotime($_product->getData('news_to_date')); ?>
									<?php if ( $timeEndNew >= $todayDate && $timeStartNew <= $todayDate): ?>
										<span class="newlabel">
											<span><?php echo __('New') ?></span>
										</span>
									<?php endif; ?>
								</div>
							</div>
							<div class="product-info">
								<div class="product details product-item-details">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<strong class="product name product-item-name xxx">
										<a class="product-item-link"
										   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"> 
											<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
										</a>
									</strong>
									<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
									
									<?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
									<?= $block->getProductDetailsHtml($_product) ?>			
									<?php if ($showDescription):?>
										<div class="product description product-item-description">
											<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
											<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
											   class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
										</div>
									<?php endif; ?>													
									<?php if ($block->getMode() == 'list') { ?>
									<div class="addto-links-icons visible-onhover">
										<div class="action-inner product-item-actions">	
											<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
														<input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
														<input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
														<?= $block->getBlockHtml('formkey') ?>
														<button type="submit"
																title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
																class="action tocart primary">
															<span>
																<i class="icon-handbag icons"></i> 
																<?= /* @escapeNotVerified */ __('Add to Cart') ?>
															</span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->isAvailable()): ?>
														<div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
											<div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
													<a href="#"
													   class="action towishlist"
													   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
													   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
													   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
													   data-action="add-to-wishlist"
													   role="button">
														<i class="icon-heart icons"></i></i>
													</a>
												<?php endif; ?>
												<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
												?>
												<a href="#"
												   class="action tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
												   role="button">
													<i class="icon-equalizer icons"></i>
												</a>
											</div>
										</div>
									</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
					<?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
				<?php endforeach; ?>
			</ol>
			</div>
		</div>
		<?= $block->getToolbarHtml() ?>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init"> 
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {
						"product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
					}
				}
			}
			</script>
		<?php endif; ?>
	</div>
<?php endif; ?>
