<div class="top-content-home">
	<div class="section-element categories-thumbnail">
		<div class="container">
			{{block class="Magento\Cms\Block\Block" block_id="home2_category_thumnail"}}
		</div>
	</div>
	<div class="section-element new_product">
		<div class="container">
			{{block class="Rokanthemes\Newproduct\Block\Newproduct" template="Rokanthemes_Newproduct::newproduct.phtml"}}
		</div>
	</div>
	<div class="section-element banner_static">
		<div class="container">
			{{block class="Magento\Cms\Block\Block" block_id="banner_static_2"}}
		</div>
	</div>

	<div class="section-element featured_product">
		<div class="container">
			{{block class="Rokanthemes\Featuredpro\Block\Featured" template="Rokanthemes_Featuredpro::featured.phtml"}}
		</div>
	</div>

	<div class="section-element section-newsletter">
		<div class="container">
			{{block class="Magento\Newsletter\Block\Subscribe" template="Magento_Newsletter::subscribe.phtml"}}
		</div>
	</div>

	<div class="section-element section-services">
		<div class="container">
			{{block class="Magento\Cms\Block\Block" block_id="shipping_support"}}
		</div>
	</div>

	<div class="section-element box-blog">
		<div class="container">
			{{block class="Rokanthemes\Blog\Block\Sidebar\Recent" template="Rokanthemes_Blog::sidebar/slider.phtml"}}
		</div>
	</div>
	<div class="section-brands">
		<div class="container">
			{{block class="Magento\Cms\Block\Block" block_id="brand-logo"}}
		</div>
	</div>
	<div class="section-element Instagram_static">
		<div class="container">
			{{block class="Magento\Cms\Block\Block" block_id="Instagram_static"}}
		</div>
	</div>
</div>
