<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ ?>
	<?php $_productCollection = $this->getProducts();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
	<?php else: ?>
	    <?php
	        $viewMode = 'grid';
	        $image = 'category_page_grid';
	        $showDescription = false;
	        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	   /*Grid*/
			/**
			 * Position for actions regarding image size changing in vde if needed
			 */
			$pos = $block->getPositioned();
		?>
	    <div class="rokan-mostviewed">
			<div class="rokan-product-heading rokan-mostviewed-heading">
				<h2><?php echo $this->getConfig('title')?></h2>
				<p class="description">
					<?php echo $this->getConfig('subdescription')?>
				</p>
			</div>
	        <?php $iterator = 1; 
				$i = 0;
				$rows = 2; ?>
			<div class="row">
				<div class="col-lg-6 hidden-xs hidden-sm hidden-md">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_image_mostview')->toHtml();?>		
				</div>
				<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
					<div class="row">
				        <ul class="owl">
				            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				            <?php foreach ($_productCollection as $_product): ?>
								<?php if($i++ %$rows == 0) echo "<li class='item best-item'>"; ?>
				                <div class="product-item" data-container="product-grid">
				                	<div class="item-inner">
			            				<?php
						                    $productImage = $block->getImage($_product, $image);
						                    if ($pos != null) {
						                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
						                            . 'top:' . $productImage->getHeight() . 'px;"';
						                    }
					                    ?>
					                    <div class="product-photo">
											<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
												<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
												<span class="image0 image-switch">
													<?php echo $productImage->toHtml(); ?>
												</span>
												<span class="image1 image-switch">
													<?php echo $productImageThumb->toHtml(); ?>
												</span>
											</a>
											<div class="addto-links-icons visible-onhover">
												<div class="action-inner">	
													<ul class="add-to-links">
														<li>
															<a href="#"
															   class="action button towishlist"
															   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
															   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
															   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
															   data-action="add-to-wishlist"
															   role="button">
																<i class="icon-heart icons"></i>
															</a>
														</li>
														<?php
															$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
														?>
														<li>
															<a href="#"
															   class="action button tocompare"
															   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
															   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
															   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
															   role="button">
															<i class="icon-equalizer icons"></i>
															</a>
														</li>
														<li class="li-quickview">
															<div class="quickview-product">
																<a href="javascript:void(0)" data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="<?php echo $block->escapeHtml(__('Quick view')); ?>" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>">
																	<i class="icon-eye icons"></i>
																</a>
														    </div>
														</li>
													</ul>
												</div>
											</div>
											<div class="addto-links-bottom">
												<ul class="add-to-links">
													<li class="li-add-cart">
														<div class="actions-add-cart">
															<div class="action-inner">
																<div class="actions-primary">
																	<?php if ($_product->isSaleable()): ?>
																		<?php $postParams = $block->getAddToCartPostParams($_product); ?>
																		<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
																			<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
																			<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
																			<?php echo $block->getBlockHtml('formkey')?>
																			<button type="submit"
																					title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																					class="action tocart primary">
																				<i class="icon-handbag icons"></i>
																				<?php echo $block->escapeHtml(__('Add to Cart')); ?>
																			</button>
																		</form>
																	<?php else: ?>
																		<?php if ($_product->getIsSalable()): ?>
																			<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
																		<?php else: ?>
																			<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
																		<?php endif; ?>
																	<?php endif; ?>
																</div>
																
															</div>
														</div>
													</li>
												</ul>
											</div>
											<div class="product-label">
												<?php if ( $_product->getFinalPrice() < $_product->getPrice() ): ?>
													<?php 
														$percent = ( ($_product->getPrice()-$_product->getFinalPrice()) / ($_product->getPrice()) )*100; 
													?>
													<span class="onsale">
														<span>-<?php echo round($percent); ?>%</span>
													</span>
												<?php endif; ?>
											</div>
										</div>
										<div class="product-info">
											<?php
												$_productNameStripped = $block->stripTags($_product->getName(), null, true);
											?>
											<strong class="product-name">
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
													<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
												</a>
											</strong>

											<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>

											<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
										</div>
				                	</div>
				                    
				                </div>
				                <?php if($i == $rows || $i == count($_productCollection)) echo '</li>'; ?>
				            <?php endforeach; ?>
				        </ul>

					</div>

				</div>

			</div>
	    </div>
	    <?php if (!$block->isRedirectToCartEnabled()) : ?>
	        <script type="text/x-magento-init">
	        {
	            "[data-role=tocart-form], .form.map.checkout": {
	                "catalogAddToCart": {}
	            }
	        }
	        </script>
			
	    <?php endif; ?>
		<script type="text/javascript">
			require([
				'jquery',
				'mage/mage',
				'rokanthemes/owl'
			], function ($) {
				'use strict';

				jQuery(".rokan-mostviewed .owl").owlCarousel({
					lazyLoad: true,
					autoPlay : false,
					items : 3,
					itemsDesktop : [1199,3],
					itemsDesktopSmall : [980,2],
					itemsTablet: [768,2],
					itemsMobile : [479,1],
					slideSpeed : 500,
					paginationSpeed : 500,
					rewindSpeed : 500,
					navigation : true,
					stopOnHover : true,
					pagination :false,
					scrollPerPage:true,
				});
			});
		</script>
	<?php endif; ?>
 
<?php } ?>