<?php 
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$title = $block->getTitle();
	$categoryIds = $block->getCategoryIds();
	$categoryIds = explode(',', $categoryIds);
	$description= $block->getDescription(); 
?>
<div class="categories-thumbnails">
	<div class="row">
		<div class="col-md-6 col-sm-6 col-xs-12 col-cat-left">
			<div class="row">
				<div class="col-xs-12">
					<div class="popcat-box">
						<?php 
						if(count($categoryIds) > 0){
							foreach($categoryIds as $key => $cate_id) {
								$cate_model =  $block->getCategory($cate_id);
								echo '
									<a href="'.$cate_model->getUrl().'"><img src="'.$this->helper('Rokanthemes\Categorytab\Helper\Data')->getThumbnailImageUrl($cate_model).'" alt="'.$cate_model->getName().'" /></a>
									<div class="cat-name">
									<h3><a href="'.$cate_model->getUrl().'">'.$cate_model->getName().'</a></h3>
									<p class="qty">('.$cate_model->getProductCount(). ' products'.')</p>  
									</div>
								';
								unset($categoryIds[$key]);
								break;
							}
						}
					   ?>
					</div>
				</div>
			</div>
			
		</div>
		<div class="col-md-6 col-sm-6 col-xs-12 col-cat-right">
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-6 col-cat-left-21">
					<div class="popcat-box">
						<?php 
							if(count($categoryIds) > 0){
								foreach($categoryIds as $key => $cate_id) {
									$cate_model =  $block->getCategory($cate_id);
									echo '
										<a href="'.$cate_model->getUrl().'"><img src="'.$this->helper('Rokanthemes\Categorytab\Helper\Data')->getThumbnailImageUrl($cate_model).'" alt="'.$cate_model->getName().'" /></a>
										<div class="cat-name"><h3><a href="'.$cate_model->getUrl().'">'.$cate_model->getName().'</a></h3>
										<p class="qty">('.$cate_model->getProductCount(). ' products'.')</p> 
										</div>
									';
									unset($categoryIds[$key]);
									break;
								}
							}
						?>
					</div>
				</div>
				<div class="col-md-6 col-sm-6 col-xs-6 col-cat-left-22">
					<div class="popcat-box">
						<?php 
							if(count($categoryIds) > 0){
								foreach($categoryIds as $key => $cate_id) {
									$cate_model =  $block->getCategory($cate_id);
									echo '
										<a href="'.$cate_model->getUrl().'"><img src="'.$this->helper('Rokanthemes\Categorytab\Helper\Data')->getThumbnailImageUrl($cate_model).'" alt="'.$cate_model->getName().'" /></a>
										<div class="cat-name">
										<h3><a href="'.$cate_model->getUrl().'">'.$cate_model->getName().'</a></h3>
										<p class="qty">('.$cate_model->getProductCount(). ' products'.')</p> 
										</div>
									';
									unset($categoryIds[$key]);
									break;
								}
							}
						?>
					</div>
				</div>
			</div>
			<div class="popcat-box">
				<?php 
				if(count($categoryIds) > 0){
					foreach($categoryIds as $key => $cate_id) {
						$cate_model =  $block->getCategory($cate_id);
						echo '
							<a href="'.$cate_model->getUrl().'"><img src="'.$this->helper('Rokanthemes\Categorytab\Helper\Data')->getThumbnailImageUrl($cate_model).'" alt="'.$cate_model->getName().'" /></a>
							<div class="cat-name">
							<h3><a href="'.$cate_model->getUrl().'">'.$cate_model->getName().'</a></h3>
							<p class="qty">('.$cate_model->getProductCount(). ' products'.')</p> 
							</div>
						';
						unset($categoryIds[$key]);
						break;
					}
				}
			   ?>
			</div>
		</div>
	</div>
</div>
