<?php 
	$data = $block->getConfig();
?>
<?php if (isset($data['general']['enable_preloaded']) && $data['general']['enable_preloaded'] == 1){ ?>
<div id="loading-fixed">
	<div id="loading-center-fixed">
		<div id="loading-center-absolute-fixed">
			<div class="loader-inner line-scale">
	          <div></div>
	          <div></div>
	          <div></div>
	          <div></div>
	          <div></div>
	        </div>
		</div>
	</div>
</div>
<script type="text/javascript">
require([
		'jquery'
	], function ($) {
		'use strict';
		$(window).load(function() {
			$('#loading-fixed').delay(500).fadeOut('slow');
		});
		$( document ).ready(function() {
			var myVarloader = setInterval(function(){ setLoaderTime() }, 2000);
			function setLoaderTime() {
				$('#loading-fixed').delay(500).fadeOut('slow');
				clearInterval(myVarloader);
			}
		});
});
</script>
<style type="text/css">
	

	#loading-fixed {
	  background-color: #fff;
	  height: 100%;
	  width: 100%;
	  position: fixed;
	  z-index: 999999;
	  margin-top: 0;
	  top: 0
	}

	#loading-center-fixed {
	  width: 100%;
	  height: 100%;
	  position: relative
	}

	#loading-center-absolute-fixed {
	  position: absolute;
	  left: 50%;
	  top: 50%;
	  height: 200px;
	  width: 200px;
	  margin-top: -120px;
	  margin-left: -100px
	}

	.spinner {
	  
	}

	@-webkit-keyframes line-scale {
	  0% {
	    -webkit-transform: scaley(1);
	            transform: scaley(1); }
	  50% {
	    -webkit-transform: scaley(0.4);
	            transform: scaley(0.4); }
	  100% {
	    -webkit-transform: scaley(1);
	            transform: scaley(1); } }
	@keyframes line-scale {
	  0% {
	    -webkit-transform: scaley(1);
	            transform: scaley(1); }
	  50% {
	    -webkit-transform: scaley(0.4);
	            transform: scaley(0.4); }
	  100% {
	    -webkit-transform: scaley(1);
	            transform: scaley(1); } }

	.line-scale > div:nth-child(1) {
	  -webkit-animation: line-scale 1s -0.4s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08);
	          animation: line-scale 1s -0.4s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08); }

	.line-scale > div:nth-child(2) {
	  -webkit-animation: line-scale 1s -0.3s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08);
	          animation: line-scale 1s -0.3s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08); }

	.line-scale > div:nth-child(3) {
	  -webkit-animation: line-scale 1s -0.2s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08);
	          animation: line-scale 1s -0.2s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08); }

	.line-scale > div:nth-child(4) {
	  -webkit-animation: line-scale 1s -0.1s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08);
	          animation: line-scale 1s -0.1s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08); }

	.line-scale > div:nth-child(5) {
	  -webkit-animation: line-scale 1s 0s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08);
	          animation: line-scale 1s 0s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08); }

	.line-scale > div {
	  background-color: #ba933e;
	  width: 4px;
	  height: 35px;
	  border-radius: 2px;
	  margin: 2px;
	  -webkit-animation-fill-mode: both;
	          animation-fill-mode: both;
	  display: inline-block; }
	.line-scale{
      margin: 100px auto;
	  width: 50px;
	  height: 40px;
	  text-align: center;
	  font-size: 10px
  	}
</style>
<?php } ?>